### ISSUE TITLE
HU 02 Denegación de servicio a usuarios de la red

### ISSUE THREAD

**Issue by Yianfri** [INF225-2023-2-P201/03-teletech-solutions#2]
Como usuario final avanzado, quiero poder denegar el servicio a una persona de la red, para poder manejar situaciones de seguridad de manera efectiva.

**Comment by Sergio1NG** [comment]
Se realiza la implementación de una función de denegación de servicio con la librería networkx

**Comment by Yianfri** [comment]
Cerrando este issue ya que la funcionalidad de denegación de servicio a usuarios de la red ha sido implementada con éxito.
