### ISSUE TITLE
HU 06 Manipulación del programa

### ISSUE THREAD

**Issue by Yianfri** [INF225-2023-2-P201/03-teletech-solutions#6]
Como usuario final, quiero utilizar un programa sin grandes conocimientos técnicos de redes, para manipular y configurar una red de área local.

**Comment by Yianfri** [comment]
Se realizaron páginas de Login y de Registro, para posteriormente ser incorporadas con la base de datos

**Comment by Yianfri** [comment]
Se realizaron las configuraciones a la red que se utilizará

**Comment by ArielBravoPonce** [comment]
Login y registro ahora están implementados con la base de datos.
